# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MLPTextFieldTestSwift' do
    pod 'MLPAutoCompleteTextField'
end

target 'MLPTextFieldTestSwiftTests' do

end

